name: Update Outside Collaborators

on:
  pull_request_target:
    branches:
    - 'main'
    paths:
    - "groups/*.yml"
    - "groups/*.yaml"
    - "repos/*.yml"
    - "repos/*.yaml"
  workflow_dispatch:

concurrency:
  group: update-outside-collaborators
  cancel-in-progress: true

jobs:
  Update-Outside-Collaborators:
    name: "Update Outside Collaborators"
    runs-on: ubuntu-latest
    environment: outside_collaborators_environment

    steps:
      - name: Set Env Variables
        run: |
          echo "OUTSIDE_COLLABORATORS_GITHUB_ORG=${{ github.repository_owner }}" >> ${GITHUB_ENV}
          echo "OUTSIDE_COLLABORATORS_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> ${GITHUB_ENV}
      - uses: actions/checkout@main
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run Handler
        run: .github/scripts/update-outside-collaborators.ps1
      
