name: Update Outside Collaborators

on:
  pull_request_target:
    branches:
    - 'main'
    paths:
    - "groups/*.yml"
    - "groups/*.yaml"
    - "repos/*.yml"
    - "repos/*.yaml"
  workflow_dispatch:

concurrency:
  group: update-outside-collaborators
  cancel-in-progress: true

jobs:
  Update-Outside-Collaborators:
    name: "Update Outside Collaborators"
    runs-on: ubuntu-latest
    environment: outside_collaborators_environment

    steps:
      - name: Set Env Variables
        shell: pwsh
        run: |
          echo "GITHUB_ORG=${{ github.repository_owner }}" >> $env:GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $env:GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Outside Collaborators
        shell: pwsh
        run: .github/scripts/update-outside-collaborators.ps1
      
